load m-output/init-ramp-f

mod TEST-M is

  inc INIT-RAMP-F .

  --- init(RTX,WTX,RWTX,CLS,DCS,REPLS,KEYS,ROPS,WOPS,RWOPS,KAD) 
  op initconf : -> Config .
  eq initconf = init(0,100,0,1,1,2,10,2,2,0,uniform) .
  op initconf50 : -> Config .
  eq initconf50 = init(50,50,0,1,1,2,10,2,2,0,uniform) .
  op initconf10 : -> Config .
  eq initconf10 = init(90,10,0,1,1,2,10,2,2,0,uniform) .
  op initconfrun : -> Config .
  eq initconfrun = run(initconf,1.0e+10) .
  op initconfrun50 : -> Config .
  eq initconfrun50 = run(initconf50,1.0e+10) .
  op initconfrun10 : -> Config .
  eq initconfrun10 = run(initconf10,1.0e+10) .
endm

set clear rules off .