load 2pc

mod INIT-2PC is including 2PC .
  ops c ch1 ch2 : -> Oid .  ops p1 p2 : -> Proposal .

  op initstate : -> Config .
  eq initstate = (start to c)
                 < c : Coord | proposals: (p1 ; p2), cohorts: (ch1 ch2), 
                               waiting: empty, results: emptyPB >
                 < ch1 : Cohort | votes: ((p1 |-> true) , (p2 |-> false)) >
                 < ch2 : Cohort | votes: ((p1 |-> true) , (p2 |-> true)) > .
endm
